# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{package_tracker}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Taras"]
  s.date = %q{2011-05-18}
  s.description = %q{PackageTracker is a ruby gem for fetching the status of a packages(UPS, FedEx, etc...) with a simple API.}
  s.email = %q{michaeltaras@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".Gemfile",
    ".autotest",
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/package_tracker.rb",
    "lib/package_tracker/carrier.rb",
    "lib/package_tracker/carriers/fedex.rb",
    "lib/package_tracker/carriers/ups.rb",
    "lib/package_tracker/carriers/usps.rb",
    "lib/package_tracker/client.rb",
    "lib/package_tracker/exceptions.rb",
    "lib/package_tracker/request.rb",
    "lib/package_tracker/response.rb",
    "package_tracker.gemspec",
    "spec/carrier/fedex_spec.rb",
    "spec/carrier/ups_spec.rb",
    "spec/carrier_spec.rb",
    "spec/fixtures/requests/ups/invalid_credentials.xml",
    "spec/fixtures/requests/ups/invalid_tracking_number.xml",
    "spec/fixtures/requests/ups/valid.xml",
    "spec/fixtures/responses/fedex/invalid_credentials.xml",
    "spec/fixtures/responses/fedex/invalid_tracking_number.xml",
    "spec/fixtures/responses/fedex/valid.xml",
    "spec/fixtures/responses/ups/invalid_credentials.xml",
    "spec/fixtures/responses/ups/invalid_tracking_number.xml",
    "spec/fixtures/responses/ups/valid.xml",
    "spec/request_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/michaeltaras/package_tracker}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{PackageTracker is a ruby gem for fetching the status of a packages(UPS, FedEx, etc...) with a simple API.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<facets>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<facets>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<facets>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

